name: CocoaPod Publish
on:
  release:
    types: [published]

jobs:
  build:
    runs-on: [macos-latest]

    steps:
      - uses: actions/checkout@v1

      - name: Clear CocoaPods cache
        uses: actions/cache@v2
        with:
          path: ~/.cocoapods
          key: ${{ runner.os }}-cocoapods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-cocoapods-
  
      - name: Install Cocoapods
        run: gem install cocoapods

      - name: Publish to Cocoapods
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
        run: |
          set -eo pipefail
          pod lib lint --allow-warnings
          pod trunk push roam-ios.podspec --allow-warnings
